tls:
  certificates:
    - certFile: "/certs/front-test.crt"
      keyFile: "/certs/front-test.key"

http:
  routers:
    front:
      rule: "Host(`front.test`)"
      service: workspace
      entryPoints:
        - https
        - websecure
      tls: {}
  services:
    workspace:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://host.docker.internal:6006"