tls:
  certificates:
    - certFile: "/certs/laravel.crt"
      keyFile: "/certs/laravel.key"

http:
  routers:
    laravel:
      rule: "Host(`laravel.test`)"
      service: laravel_service
      entryPoints:
        - https
        - websecure
      tls: {}
  services:
    laravel_service:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://nginx:80"