FROM quay.io/soketi/soketi:latest-16-debian

LABEL maintainer="Oleh Demchenko <blacklife1992@gmail.com>"

COPY config.json /app/bin/config.json

CMD ["--config=/app/bin/config.json"]

EXPOSE 6001 9601
